"""initial_schema

Revision ID: 8ef28bafe420
Revises: 
Create Date: 2026-09-06 08:25:23.423189

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8ef28bafe420'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ig_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('profile_pic_url', sa.Text(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ig_users_username'), 'ig_users', ['username'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ig_user_id', sa.Integer(), nullable=False),
    sa.Column('ig_username', sa.String(length=100), nullable=False),
    sa.Column('session_data', sa.String(), nullable=False),
    sa.Column('plan_b_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ig_user_id')
    )
    op.create_table('action_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('ig_user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ig_user_id'], ['ig_users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_log_session_id'), 'action_log', ['session_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('shortcode', sa.String(length=50), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shortcode')
    )
    op.create_index(op.f('ix_posts_session_id'), 'posts', ['session_id'], unique=False)
    op.create_index(op.f('ix_posts_taken_at'), 'posts', ['taken_at'], unique=False)
    op.create_table('relationships',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('ig_user_id', sa.Integer(), nullable=False),
    sa.Column('we_follow', sa.Boolean(), nullable=False),
    sa.Column('they_follow', sa.Boolean(), nullable=False),
    sa.Column('we_follow_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('they_follow_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ig_user_id'], ['ig_users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'ig_user_id')
    )
    op.create_index(op.f('ix_relationships_they_follow'), 'relationships', ['they_follow'], unique=False)
    op.create_index(op.f('ix_relationships_we_follow'), 'relationships', ['we_follow'], unique=False)
    op.create_table('sync_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('celery_task_id', sa.String(length=200), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('processed_items', sa.Integer(), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('ig_user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('interacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ig_user_id'], ['ig_users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ig_user_id', 'post_id', 'interaction_type')
    )
    op.create_index(op.f('ix_interactions_ig_user_id'), 'interactions', ['ig_user_id'], unique=False)
    op.create_index(op.f('ix_interactions_post_id'), 'interactions', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interactions_post_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_ig_user_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_table('sync_jobs')
    op.drop_index(op.f('ix_relationships_we_follow'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_they_follow'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_posts_taken_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_session_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_action_log_session_id'), table_name='action_log')
    op.drop_table('action_log')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_ig_users_username'), table_name='ig_users')
    op.drop_table('ig_users')
    # ### end Alembic commands ###
